apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "node-db-app"
  annotations:
    "humanitec.com/orgId": "htc-demo-41"
    "humanitec.com/appId": "node-db-app"
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
